# This file is used to configure the clangd index server.
# location: ~/.config/clangd/config.yaml
# ref: https://github.com/clangd/chrome-remote-index/blob/main/docs/index.md

If:
  PathMatch: ~/code/chromium/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: ~/code/chromium/src/

---

If:
  PathMatch: /mnt/code/chromium/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: /mnt/code/chromium/src/

---

If:
  PathMatch: /mnt/code/chromium2/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: /mnt/code/chromium2/src/
