# This file is used to configure the clangd index server.
# location: ~/.config/clangd/config.yaml
# ref: https://github.com/clangd/chrome-remote-index/blob/main/docs/index.md
# ref: https://github.com/chromium/chromium/blob/main/docs/clangd.md#getting-clangd
# NOTE: ~ should be replaced with an absolute path.
# NOTE: don't forget to call 
#   ./tools/clang/scripts/generate_compdb.py -o compile_commands.json -p ./out/Default/

If:
  PathMatch: /home/cg/google/chromium/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: /home/cg/google/chromium/src/

---

If:
  PathMatch: /home/cg/google/chromium1/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: /home/cg/google/chromium1/src/

---

If:
  PathMatch: /home/cg/google/chromium2/src/.*
Index:
  External:
    Server: linux.clangd-index.chromium.org:5900
    MountPoint: /home/cg/google/chromium2/src/
